### ISSUE TITLE
`mpm_solver.project_outside` causes particles to overlap and remain interpenetrating

### ISSUE THREAD

**Issue by maxkra15** [newton-physics/newton#1055]
**Description**  
When using the MPM solver, the collision projection step `mpm_solver.project_outside` appears to push particles *into* each other instead of separating them. Once particles become interpenetrated, the solver does not resolve this in subsequent steps, which results in permanently overlapping particles and unrealistic compaction behavior.

This effect is particularly noticeable when interacting with convex shapes (e.g., a bucket), where the projection seems to compress the material inward rather than resolve penetration.

Example (particles collapsing into each other):  
![Image](https://github.com/user-attachments/assets/bf8575c3-713e-4fbc-a575-0c28d764fd85)

**Expected Behavior**  
Particles should be separated when resolving collisions, and the solver should prevent them from remaining interpenetrated in later steps.

**Actual Behavior**  
Particles are projected into each other during the collision resolution stage, and stay overlapped over time. This results in non-physical compaction and material collapse.

**Reproduction**  
I can provide a minimal test script to reproduce the issue if needed.

**Questions**  
1. Is this a known limitation/behavior of the current projection step?
2. Is there a recommended workaround (i started implementing a custom projection kernel with aditional seperation)?

Thanks!

**Comment by gdaviet** [comment]
Yes, unfortunately this is a known issue when the variations in collider normal are large compared to the voxel size. I am working on subgrid collision resolution to handle this case better, but unfortunately in the meantime there is no great solution, other than increasing the grid resolution or the collider thickness. In some cases, setting `mpm_options.collider_normal_from_sdf_gradient = True` will help, but not sure that this will be the case here.

**Comment by maxkra15** [comment]
@gdaviet Alright thanks, I will try these and maybe come up with something to mitigate the effects.

**Comment by maxkra15** [comment]
@gdaviet Do you have a timeline when this issue will be directly addressed?

**Comment by gdaviet** [comment]
Hi @maxkra15, the subgrid collision work has been merged to the main branch. You can now specify a basis on which nodes the collision constraints should be solved, for instance, "collider-basis=S2" (add constraints to the middle of each grid edge), or "collision-basis=pic" (add collision contraint per particle)
To visualize the effects of this basis, you can enable "Show Normals" in the example_mpm_granular example 

If you still have an asset for which the collisions are not properly resolved, it would be great if you could share a representative example

<img width="832" height="625" alt="Image" src="https://github.com/user-attachments/assets/d2d1b7fb-6b23-4de8-b96c-45f4874597a1" />

**Comment by maxkra15** [comment]
Hi @gdaviet, thanks for the update,I saw the PR.

One thing I noticed in the `example_mpm_granular.py` example: with **sparse grid** everything behaves as expected, but with **fixed grid** both the *cube collider* and *concave collider* setups show particles collapsing/interpenetrating, even when using `collision-basis=S2` or `collision-basis=pic`. This seems to have to do with the fixed grid origin computation/grid bounds (on first look).

Could you check whether you can reproduce this on your side?

Attaching an image here:

<img width="1013" height="643" alt="Image" src="https://github.com/user-attachments/assets/6bb17fa4-b562-423e-91f8-6a48dc1ef4b4" />

Add On: Confirmed that this is the bounds that need to be set such that colliders are also included properly. Passing these directly solved the issue for me. I will report once I have results for our custom environments.

**Comment by gdaviet** [comment]
@maxkra15  in `example_mpm_granular` if you specify `grid_type=fixed` you need to manually specify a non-zero padding as well, for instance 
```
uv run newton/examples/mpm/example_mpm_granular.py --grid-type fixed --grid-padding 50
```

For a fixed grid the padding indicates the number of empty grid cells to pre-define around the initial particles, so they have somewhere to move (the simulation will then be run on the active subset of this padded grid at each step)

**Comment by maxkra15** [comment]
@gdaviet thanks for the quick pointer, I overlooked the padding parameter default set to 0. I ll test this in our custom setups and report back.

**Comment by maxkra15** [comment]
Hi @gdaviet

We ve tested various configurations but still encounter **particle-particle interpenetration** with thin colliders:

**Current Setup:**
- Thin end-effector (shovel) pushing into granular material
- Using `project_outside()` for collider-particle collision
- `collider_basis = "S2"`

**Observed Behavior:**
When the shovel compresses particles  they **interpenetrate each other** and remain in a stable overlapping state. The compressive stress that should separate them appears to not be resolved ,particles amass on top of each other creating non-physical compaction/collapse: 

https://github.com/user-attachments/assets/9363c9f9-2d70-49a5-8ce0-9556144e5ee5

**Hypothesis:**

The `project_outside()` step projects particles outside the collider, but in doing so pushes multiple particles into the **same spatial location**. The implicit solver should then resolve this via elastic stresses (particles overlapping → high density → compressive stress → separation). However, these overlapping configurations appear **stable** in the implicit solve - the expected separating forces don t materialize.

Could this be related to:
1. The rigidification of velocity gradients (`vel_grad = 0.5 * (vel_grad - wp.transpose(vel_grad))`) dampening the elastic response?
2. The projection creating particle states that fall outside the solver's convergence basin?
3. Mass lumping or grid-transfer losing the inter-particle stress information?

**Questions:**
1. Is this a known limitation of implicit MPM with aggressive projection? We seem to be able to mitigate this with explicit MPM implementations in a separate implementation.
2. Any recommended particle spacing or settings to prevent stable interpenetration?

I unfortunately cannot provide a script to reproduce this/would have to ask for permission, lmk if that would help.

**Comment by gdaviet** [comment]
Hi @maxkra15, thanks for the update.

This is not really a matter of explicit vs implicit, but rather velocity-level vs position-level collision handling.
It is indeed expected that the current projection operator does not separate particles; as it is, it is a destructive operator (it moves the particles without changing the velocity field, and thus the deformation gradient stored at particles). It is mostly a failsafe, but should not be relied upon for normal collision handling. 

To ensure particle separation, we could replace this projection with a force that progressively depenetrates the particles, in a Baumgarte stabilization sort of way. But that would be a stiff explicit force, with the usual consequences on simulation stability.
For thin objects like this, another option would be to discretize the mesh as "inactive" particles (densely sampling particles in the mesh interior and setting `model.particle_flags[particle] = 0`), so that their velocity is directly rasterized to the grid. This should preserve the stability, however this can give rise to numerical sticking artifacts (we can't enforce the Signorini-Coulomb conditions exactly).

Ideally, we should still be able to use the normal collision resolution scheme, without projection, for this. The most accurate setting currently would be to set collider-basis="picN", for example "pic8" or "pic27" (the number is required for graph-capturability, otherwise you don't need to specify it).
Currently, it is possible that either the normals are rasterized too sparsely, have wrong sign, or that the velocity set on the collider mesh does not exactly match the finite-differenced positions, but that is hard to test without the script.

In short, what I would suggest is:
  - First try the simulation with `strain-basis="pic27" ` and disabling the projection. You can also try setting to `_SDF_SIGN_FROM_AVERAGE_NORMAL=False` in `rasterized_collisions.py`
  - If that does not work, using a kinematic particle-based representation instead of a mesh

**Comment by maxkra15** [comment]
Thanks again for the quick reply, the suggestions and the time you took to explain this. I will try all of these and come back to you. (the discretization using particles was an idea we just discussed internally)

**Comment by maxkra15** [comment]
Hi @gdaviet

Quick update: while testing various collision configurations, I noticed what appears to be a bug in the velocity calculation for rigid-body-attached meshes in `rasterized_collisions.py`.

The original code only computed the rigid body velocity contribution but was missing the mesh's own velocity:
```python
sdf_vel = wp.quat_rotate(b_rot, sdf_vel)
sdf_grad = wp.normalize(wp.quat_rotate(b_rot, sdf_grad))

# Assumes linear/angular velocities in world frame
b_v = wp.spatial_top(body_qd[body_id])
b_w = wp.spatial_bottom(body_qd[body_id])
sdf_vel = b_v + wp.cross(b_w, wp.quat_rotate(b_rot, closest_point - collider.body_com[body_id]))
```

I believe it should properly combine both the mesh velocity and rigid body velocity:
```python
sdf_grad = wp.normalize(wp.quat_rotate(b_rot, sdf_grad))

# Assumes linear/angular velocities in world frame
b_v = wp.spatial_top(body_qd[body_id])
b_w = wp.spatial_bottom(body_qd[body_id])
mesh_vel_world = wp.quat_rotate(b_rot, sdf_vel)
rigid_vel = b_v + wp.cross(b_w, wp.quat_rotate(b_rot, closest_point - collider.body_com[body_id]))
sdf_vel = mesh_vel_world + rigid_vel
```

Is this:
1. This is indeed a bug that should be fixed, or
2. The mesh velocity contribution was intentionally omitted for some reason i m missing

Interestingly, I observe good collision properties when using a static mesh that I simply refit every step, but when using the mesh extracted from the body (which should be the proper approach), we see tunneling and bad collision handling. 

If it would help, I d be happy to share our current setup/code for you to take a look at, would need to share it non-public though.

Thanks for all your help on this!

**Comment by gdaviet** [comment]
Great finds @maxkra15 ! 
The fact that you get better collision response with a static mesh than with a mesh extracted from the body is indeed a good indicator that something is wrong the inferred velocity.

The missing mesh velocity is definitely a bug, and your fix looks correct to me; however, for rigid bodies the shape mesh velocity will usually be 0, so unfortunately I don't think this affects your use case. Another thing that could be worth trying is using a finite-difference version of the velocity at the collider point rather than the rigid velocity

Having a simple repro of your setup, even if it is not using the real assets, would be very useful -- sharing privately is definitely an option

**Comment by maxkra15** [comment]
Thanks @gdaviet I already had started working on a finite-difference velocity collider. And it works very well for my environment - see my PR [here](https://github.com/newton-physics/newton/pull/1227) I am not sure if this is how you would like to implement this, so feel free to not merge and implement this "your style". Edit: this also includes the solution to the mesh velocity issue, i forgot to mention this in the PR.

**Comment by Idate96** [comment]
@maxkra15 could share a reproducible example with @gdaviet? sharing the assets in private is not a problem. if having the mesh finite difference velocity collider is not the end of the story :)
